services:
    laravel:
        container_name: laravel_app
        build:
            context: invest-real-estate
        volumes:
            - ./:/var/www
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - laravel

    nginx:
        container_name: nginx_app
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        depends_on:
            - laravel
        networks:
            - laravel

    mysql:
        container_name: mysql_app
        image: mysql:8.0
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin_test
            MYSQL_DATABASE: real_estate_investment
            MYSQL_USER: admin_test
            MYSQL_PASSWORD: admin_test
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
            retries: 5
            timeout: 10s
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
        driver: bridge
